#!/usr/bin/env bash
# bash wrapper for post-install.py
pacman -Sy --needed python wget sudo
mkdir ~/.config/davros
cd ~/.config/davros
wget https://davros.netlify.app/pkg.txt https://davros.netlify.app/post_install.py https://davros.netlify.app/aur-pkg.txt https://davros.netlify.app/upgrade.sh
python post_install.py
